
#./sel_OBbfvtx data cut1_OBbfvtx root://eoscms.cern.ch//eos/cms/store/user/gechen/crab3_run/DoubleMuParked/BuToKMuMu_Data_2012A_8TeV_v8/BToKMuMu_1.root ../RootFiles/Data_cut1_OBbfvtx/BToKMuMu_Data_2012A_v8_cut1_OBbfvtx_1.root
./sel_OBbfvtx data cut1_OBbfvtx root://eoscms.cern.ch//eos/cms/store/user/gechen/crab3_run/DoubleMuParked/BuToKMuMu_Data_2012A_8TeV_v8/BToKMuMu_2.root ../RootFiles/Data_cut1_OBbfvtx/BToKMuMu_Data_2012A_v8_cut1_OBbfvtx_2.root
./sel_OBbfvtx data cut1_OBbfvtx root://eoscms.cern.ch//eos/cms/store/user/gechen/crab3_run/DoubleMuParked/BuToKMuMu_Data_2012A_8TeV_v8/BToKMuMu_3.root ../RootFiles/Data_cut1_OBbfvtx/BToKMuMu_Data_2012A_v8_cut1_OBbfvtx_3.root
./sel_OBbfvtx data cut1_OBbfvtx root://eoscms.cern.ch//eos/cms/store/user/gechen/crab3_run/DoubleMuParked/BuToKMuMu_Data_2012A_8TeV_v8/BToKMuMu_4.root ../RootFiles/Data_cut1_OBbfvtx/BToKMuMu_Data_2012A_v8_cut1_OBbfvtx_4.root

./sel_OBbfvtx data cut1_OBbfvtx root://eoscms.cern.ch//eos/cms/store/user/gechen/crab3_run/MuOniaParked/BuToKMuMu_Data_2012B_8TeV_v8/BToKMuMu_Data_2012B_1.root ../RootFiles/Data_cut1_OBbfvtx/BToKMuMu_Data_2012B_v8_cut1_OBbfvtx_1.root
./sel_OBbfvtx data cut1_OBbfvtx root://eoscms.cern.ch//eos/cms/store/user/gechen/crab3_run/MuOniaParked/BuToKMuMu_Data_2012B_8TeV_v8/BToKMuMu_Data_2012B_2.root ../RootFiles/Data_cut1_OBbfvtx/BToKMuMu_Data_2012B_v8_cut1_OBbfvtx_2.root
./sel_OBbfvtx data cut1_OBbfvtx root://eoscms.cern.ch//eos/cms/store/user/gechen/crab3_run/MuOniaParked/BuToKMuMu_Data_2012B_8TeV_v8/BToKMuMu_Data_2012B_3.root ../RootFiles/Data_cut1_OBbfvtx/BToKMuMu_Data_2012B_v8_cut1_OBbfvtx_3.root
./sel_OBbfvtx data cut1_OBbfvtx root://eoscms.cern.ch//eos/cms/store/user/gechen/crab3_run/MuOniaParked/BuToKMuMu_Data_2012B_8TeV_v8/BToKMuMu_Data_2012B_4.root ../RootFiles/Data_cut1_OBbfvtx/BToKMuMu_Data_2012B_v8_cut1_OBbfvtx_4.root
./sel_OBbfvtx data cut1_OBbfvtx root://eoscms.cern.ch//eos/cms/store/user/gechen/crab3_run/MuOniaParked/BuToKMuMu_Data_2012B_8TeV_v8/BToKMuMu_Data_2012B_5.root ../RootFiles/Data_cut1_OBbfvtx/BToKMuMu_Data_2012B_v8_cut1_OBbfvtx_5.root
./sel_OBbfvtx data cut1_OBbfvtx root://eoscms.cern.ch//eos/cms/store/user/gechen/crab3_run/MuOniaParked/BuToKMuMu_Data_2012B_8TeV_v8/BToKMuMu_Data_2012B_6.root ../RootFiles/Data_cut1_OBbfvtx/BToKMuMu_Data_2012B_v8_cut1_OBbfvtx_6.root
./sel_OBbfvtx data cut1_OBbfvtx root://eoscms.cern.ch//eos/cms/store/user/gechen/crab3_run/MuOniaParked/BuToKMuMu_Data_2012B_8TeV_v8/BToKMuMu_Data_2012B_7.root ../RootFiles/Data_cut1_OBbfvtx/BToKMuMu_Data_2012B_v8_cut1_OBbfvtx_7.root
./sel_OBbfvtx data cut1_OBbfvtx root://eoscms.cern.ch//eos/cms/store/user/gechen/crab3_run/MuOniaParked/BuToKMuMu_Data_2012B_8TeV_v8/BToKMuMu_Data_2012B_8.root ../RootFiles/Data_cut1_OBbfvtx/BToKMuMu_Data_2012B_v8_cut1_OBbfvtx_8.root
./sel_OBbfvtx data cut1_OBbfvtx root://eoscms.cern.ch//eos/cms/store/user/gechen/crab3_run/MuOniaParked/BuToKMuMu_Data_2012B_8TeV_v8/BToKMuMu_Data_2012B_9.root ../RootFiles/Data_cut1_OBbfvtx/BToKMuMu_Data_2012B_v8_cut1_OBbfvtx_9.root
./sel_OBbfvtx data cut1_OBbfvtx root://eoscms.cern.ch//eos/cms/store/user/gechen/crab3_run/MuOniaParked/BuToKMuMu_Data_2012B_8TeV_v8/BToKMuMu_Data_2012B_10.root ../RootFiles/Data_cut1_OBbfvtx/BToKMuMu_Data_2012B_v8_cut1_OBbfvtx_10.root
./sel_OBbfvtx data cut1_OBbfvtx root://eoscms.cern.ch//eos/cms/store/user/gechen/crab3_run/MuOniaParked/BuToKMuMu_Data_2012B_8TeV_v8/BToKMuMu_Data_2012B_11.root ../RootFiles/Data_cut1_OBbfvtx/BToKMuMu_Data_2012B_v8_cut1_OBbfvtx_11.root
./sel_OBbfvtx data cut1_OBbfvtx root://eoscms.cern.ch//eos/cms/store/user/gechen/crab3_run/MuOniaParked/BuToKMuMu_Data_2012B_8TeV_v8/BToKMuMu_Data_2012B_12.root ../RootFiles/Data_cut1_OBbfvtx/BToKMuMu_Data_2012B_v8_cut1_OBbfvtx_12.root
./sel_OBbfvtx data cut1_OBbfvtx root://eoscms.cern.ch//eos/cms/store/user/gechen/crab3_run/MuOniaParked/BuToKMuMu_Data_2012B_8TeV_v8/BToKMuMu_Data_2012B_13.root ../RootFiles/Data_cut1_OBbfvtx/BToKMuMu_Data_2012B_v8_cut1_OBbfvtx_13.root
./sel_OBbfvtx data cut1_OBbfvtx root://eoscms.cern.ch//eos/cms/store/user/gechen/crab3_run/MuOniaParked/BuToKMuMu_Data_2012B_8TeV_v8/BToKMuMu_Data_2012B_14.root ../RootFiles/Data_cut1_OBbfvtx/BToKMuMu_Data_2012B_v8_cut1_OBbfvtx_14.root
