./fit PlotBlxsig_CosThetaL ../CutASelection/RootFiles/Data_2012_8TeV_v4_AllCut.root 0
./fit PlotBlxsig_CosThetaL ../CutASelection/RootFiles/Data_2012_8TeV_v4_AllCut.root 1
./fit PlotBlxsig_CosThetaL ../CutASelection/RootFiles/Data_2012_8TeV_v4_AllCut.root 2
./fit PlotBlxsig_CosThetaL ../CutASelection/RootFiles/Data_2012_8TeV_v4_AllCut.root 4
./fit PlotBlxsig_CosThetaL ../CutASelection/RootFiles/Data_2012_8TeV_v4_AllCut.root 6
./fit PlotBlxsig_CosThetaL ../CutASelection/RootFiles/Data_2012_8TeV_v4_AllCut.root 7
./fit PlotBlxsig_CosThetaL ../CutASelection/RootFiles/Data_2012_8TeV_v4_AllCut.root 8
./fit PlotBlxsig_CosThetaL ../CutASelection/RootFiles/Data_2012_8TeV_v4_AllCut.root 9
./fit PlotBlxsig_CosThetaL ../CutASelection/RootFiles/Data_2012_8TeV_v4_AllCut.root 10
